name: rvm

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: set up zulu JDK 17 
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'zulu'
    - name: download youtube 16.40.36
      run: curl https://transfer.sh/get/1RUeoGrqen/com.google.android.youtube_16.40.36-1523705280_minAPI21%28arm64-v8a,armeabi-v7a,x86,x86_64%29%28nodpi%29_apkmirror.com.apk --output yt.apk
    - name: download revanced cli 3.1.1 
      run: curl -L https://github.com/ReVanced/revanced-cli/releases/download/v3.1.1/revanced-cli-3.1.1-all.jar --output revanced-cli.jar
    - name: download revanced patches 
      run: curl -L https://github.com/d4n3436/revanced-patches-android5/releases/download/v2.161.0/revanced-patches-2.161.0.jar -O
    - name: download revanced integrations
      run: curl -L https://github.com/d4n3436/revanced-integrations/releases/download/v0.96.7/revanced-integrations-0.96.7.apk -O
    - name: patch app
      run: java -jar revanced-cli.jar patch yt.apk -p -o ytrv5.apk -b revanced-patches-2.161.0.jar -m revanced-integrations-0.96.7.apk
    - name: upload this mf
      uses: actions/upload-artifact@v3
      with:
        name: app
        path: ytrv5.apk
