name: rvm

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'zulu'
    - name: download youtube apk
      run: curl https://transfer.sh/get/1RUeoGrqen/com.google.android.youtube_16.40.36-1523705280_minAPI21%28arm64-v8a,armeabi-v7a,x86,x86_64%29%28nodpi%29_apkmirror.com.apk --output yt.apk
    - name: download cli 3.1.1
