name: oco

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Clone
      run: git clone https://github.com/MateriiApps/OpenCord 
    - name: set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'zulu'
        cache: gradle
     
    - name: Grant execute permission for gradlew
      run: chmod +x OpenCord/gradlew
    - name: Build with Gradle
      run: cd OpenCord && ./gradlew app:assembleDebug
    - name: Upload APK
      uses: actions/upload-artifact@v2
      with:
        name: app
        path: OpenCord/app/build/outputs/apk/debug/app-debug.apk
