name: lawnre

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        repo: LawnchairLauncher/lawnchair
        ref: expose-feed-preferences
    - name: set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle
    
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew assembleRelease
    - name: Sign app APK
      uses: r0adkll/sign-android-release@v1
      id: sign_app
      with:
        releaseDirectory: revanced-manager/app/build/outputs/apk/release
        signingKeyBase64: ${{ secrets.SK }}
        alias: ${{ secrets.AS }}
        keyStorePassword: ${{ secrets.KSP }}
        keyPassword: ${{ secrets.KP }}
      env:
        BUILD_TOOLS_VERSION: "30.0.2"
    - name: Upload APK
      uses: actions/upload-artifact@v3
      with:
        name: app
        path: ${{steps.sign_app.outputs.signedReleaseFile}}
